import logging
from dataclasses import dataclass
from typing import List, Tuple, Any

from sentence_transformers import SentenceTransformer

from .chunker import build_chunks, CurriculumChunk

logger = logging.getLogger(__name__)

@dataclass
class EmbeddedChunk:
    chunk: CurriculumChunk
    embedding: Any

class CurriculumEmbedder:
    """
    Responsible for generating and managing embeddings for curriculum chunks.
    """
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        """
        Initializes the CurriculumEmbedder.
        The embedding model is loaded only once during initialization.
        
        Args:
            model_name (str): The name of the SentenceTransformer model to use.
        """
        logger.info(f"Loading sentence-transformers model: {model_name}")
        self.model = SentenceTransformer(model_name)

    def process_and_embed(self) -> List[EmbeddedChunk]:
        """
        Loads all curriculum chunks and generates embeddings for them.
        
        Returns:
            List[EmbeddedChunk]: A list of EmbeddedChunk objects. Each contains 
            the original CurriculumChunk object and its corresponding embedding array,
            in the exact same order as they were generated by build_chunks().
        """
        logger.info("Retrieving curriculum chunks...")
        chunks = build_chunks()

        if not chunks:
            logger.warning("No chunks found to embed.")
            return []

        logger.info(f"Generating embeddings for {len(chunks)} chunks...")
        
        # Extract just the formatted text from each chunk for the model
        texts_to_embed = [chunk.text for chunk in chunks]
        
        # Encode all texts into embeddings in one batch operation
        embeddings = self.model.encode(
            texts_to_embed,
            convert_to_numpy=True,
            show_progress_bar=False
        )

        # Zip pairs each chunk with its resulting embedding seamlessly
        chunk_embeddings = [
            EmbeddedChunk(chunk=chunk, embedding=emb)
            for chunk, emb in zip(chunks, embeddings)
        ]
        
        logger.info("Embeddings generated successfully.")
        return chunk_embeddings
